<script setup lang="ts">
import {
  Activity,
  AlertTriangle,
  ArrowLeft,
  AudioLines,
  Blocks,
  BookCopy,
  BookOpen,
  Box,
  Boxes,
  Braces,
  Camera,
  Check,
  CheckCircle2,
  ChevronRight,
  CircleDot,
  CircleX,
  CloudSun,
  Code2,
  CodeXml,
  CookingPot,
  Copy,
  Crosshair,
  Cuboid,
  Database,
  Download,
  EllipsisVertical,
  ExternalLink,
  Eye,
  EyeOff,
  FileJson2,
  FileText,
  Film,
  FolderKanban,
  FolderOpen,
  FolderOutput,
  FolderPlus,
  FolderTree,
  Gem,
  Globe2,
  Grid2X2,
  Hammer,
  House,
  Image,
  ImagePlus,
  Info,
  Languages,
  Layers3,
  Leaf,
  ListTree,
  Lock,
  LockOpen,
  Magnet,
  Maximize2,
  Menu,
  Minimize2,
  Monitor,
  Moon,
  MousePointer2,
  Move3d,
  Music2,
  Network,
  Package,
  PackageOpen,
  PaintBucket,
  Palette,
  PanelTop,
  Pencil,
  Pin,
  PinOff,
  Plus,
  PlusCircle,
  Rabbit,
  Redo2,
  Rotate3d,
  Save,
  Scaling,
  Search,
  Settings,
  Shapes,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  Sun,
  Terminal,
  Trash2,
  Undo2,
  Upload,
  WifiOff,
  Wrench,
  X,
  type LucideIcon,
} from '@lucide/vue'

const props = withDefaults(
  defineProps<{
    name: string
    size?: number
    strokeWidth?: number
    label?: string
  }>(),
  {
    size: 24,
    strokeWidth: 2,
    label: undefined,
  },
)

const icons: Record<string, LucideIcon> = {
  activity: Activity,
  'alert-triangle': AlertTriangle,
  'arrow-left': ArrowLeft,
  'audio-lines': AudioLines,
  blocks: Blocks,
  'book-copy': BookCopy,
  'book-open': BookOpen,
  box: Box,
  boxes: Boxes,
  braces: Braces,
  camera: Camera,
  check: Check,
  'check-circle': CheckCircle2,
  'chevron-right': ChevronRight,
  'circle-dot': CircleDot,
  'circle-x': CircleX,
  'cloud-sun': CloudSun,
  code: Code2,
  'code-xml': CodeXml,
  'cooking-pot': CookingPot,
  copy: Copy,
  crosshair: Crosshair,
  cuboid: Cuboid,
  database: Database,
  download: Download,
  'more-vertical': EllipsisVertical,
  'external-link': ExternalLink,
  eye: Eye,
  'eye-off': EyeOff,
  'file-json': FileJson2,
  file: FileText,
  film: Film,
  folder: FolderKanban,
  'folder-open': FolderOpen,
  'folder-output': FolderOutput,
  'folder-plus': FolderPlus,
  'folder-tree': FolderTree,
  gem: Gem,
  globe: Globe2,
  grid: Grid2X2,
  hammer: Hammer,
  github: Code2,
  home: House,
  image: Image,
  'image-plus': ImagePlus,
  info: Info,
  languages: Languages,
  layers: Layers3,
  leaf: Leaf,
  'list-tree': ListTree,
  lock: Lock,
  unlock: LockOpen,
  magnet: Magnet,
  maximize: Maximize2,
  menu: Menu,
  restore: Minimize2,
  monitor: Monitor,
  moon: Moon,
  pointer: MousePointer2,
  'move-3d': Move3d,
  music: Music2,
  network: Network,
  package: Package,
  'package-open': PackageOpen,
  'paint-bucket': PaintBucket,
  palette: Palette,
  panel: PanelTop,
  pencil: Pencil,
  pin: Pin,
  'pin-off': PinOff,
  plus: Plus,
  'plus-circle': PlusCircle,
  rabbit: Rabbit,
  redo: Redo2,
  'rotate-3d': Rotate3d,
  save: Save,
  scale: Scaling,
  search: Search,
  settings: Settings,
  shapes: Shapes,
  shield: ShieldCheck,
  sliders: SlidersHorizontal,
  sparkles: Sparkles,
  sun: Sun,
  terminal: Terminal,
  trash: Trash2,
  undo: Undo2,
  upload: Upload,
  'wifi-off': WifiOff,
  wrench: Wrench,
  x: X,
}

const icon = icons[props.name] ?? Box
</script>

<template>
  <component
    :is="icon"
    :size="size"
    :stroke-width="strokeWidth"
    :aria-label="label"
    :aria-hidden="label ? undefined : 'true'"
    focusable="false"
  />
</template>
