<script setup lang="ts">
import {
  Activity,
  AlertTriangle,
  ArrowLeft,
  AudioLines,
  Blocks,
  BookOpen,
  Box,
  Boxes,
  Braces,
  Check,
  CheckCircle2,
  ChevronRight,
  CircleDot,
  CircleX,
  Code2,
  CookingPot,
  Copy,
  Camera,
  Crosshair,
  Database,
  EllipsisVertical,
  ExternalLink,
  FileText,
  Eye,
  EyeOff,
  FolderKanban,
  FolderOpen,
  FolderOutput,
  FolderPlus,
  Gem,
  House,
  Info,
  Languages,
  Layers3,
  ImagePlus,
  ListTree,
  Lock,
  LockOpen,
  Magnet,
  Menu,
  Maximize2,
  Minimize2,
  Monitor,
  MousePointer2,
  Moon,
  Move3d,
  Package,
  Palette,
  Pencil,
  Plus,
  Rabbit,
  Redo2,
  Rotate3d,
  Save,
  Search,
  Settings,
  ShieldCheck,
  Sparkles,
  Scaling,
  SlidersHorizontal,
  Sun,
  Terminal,
  Trash2,
  Upload,
  Undo2,
  WifiOff,
  X,
  type LucideIcon,
} from '@lucide/vue'

const props = withDefaults(
  defineProps<{
    name: string
    size?: number
    strokeWidth?: number
    label?: string
  }>(),
  {
    size: 24,
    strokeWidth: 2,
    label: undefined,
  },
)

const icons: Record<string, LucideIcon> = {
  activity: Activity,
  'alert-triangle': AlertTriangle,
  'arrow-left': ArrowLeft,
  'audio-lines': AudioLines,
  blocks: Blocks,
  'book-open': BookOpen,
  box: Box,
  boxes: Boxes,
  braces: Braces,
  check: Check,
  'check-circle': CheckCircle2,
  'chevron-right': ChevronRight,
  'circle-dot': CircleDot,
  'circle-x': CircleX,
  code: Code2,
  'cooking-pot': CookingPot,
  copy: Copy,
  camera: Camera,
  crosshair: Crosshair,
  database: Database,
  'more-vertical': EllipsisVertical,
  'external-link': ExternalLink,
  file: FileText,
  eye: Eye,
  'eye-off': EyeOff,
  folder: FolderKanban,
  'folder-open': FolderOpen,
  'folder-output': FolderOutput,
  'folder-plus': FolderPlus,
  gem: Gem,
  github: Code2,
  home: House,
  info: Info,
  languages: Languages,
  layers: Layers3,
  'image-plus': ImagePlus,
  'list-tree': ListTree,
  lock: Lock,
  unlock: LockOpen,
  magnet: Magnet,
  menu: Menu,
  maximize: Maximize2,
  restore: Minimize2,
  monitor: Monitor,
  pointer: MousePointer2,
  moon: Moon,
  'move-3d': Move3d,
  package: Package,
  palette: Palette,
  pencil: Pencil,
  plus: Plus,
  rabbit: Rabbit,
  redo: Redo2,
  'rotate-3d': Rotate3d,
  save: Save,
  search: Search,
  settings: Settings,
  shield: ShieldCheck,
  sparkles: Sparkles,
  scale: Scaling,
  sliders: SlidersHorizontal,
  sun: Sun,
  terminal: Terminal,
  trash: Trash2,
  upload: Upload,
  undo: Undo2,
  'wifi-off': WifiOff,
  x: X,
}

const icon = icons[props.name] ?? Box
</script>

<template>
  <component
    :is="icon"
    :size="size"
    :stroke-width="strokeWidth"
    :aria-label="label"
    :aria-hidden="label ? undefined : 'true'"
    focusable="false"
  />
</template>
